from .MTL_model import MTL_model
from .STL_model import STL_model
from .cls_model import cls_model
from .MTL_model_v2 import MTL_UNet
from .MTL_model_v2 import MTL_UNet_v2
from .MTL_model_v2 import get_efficientunet_b0
from .MTL_model_v2 import get_efficientunet_b3
from .MTL_model_v2 import get_efficientunet_b5
from .MTL_model_v2 import get_efficientunet_b7
from .MTL_model_v2 import get_efficientunet_b0_cls
from .MTL_model_v2 import get_efficientunet_b3_cls
from .MTL_model_v2 import get_efficientunet_b0_seg
from .MTL_model_v2 import get_efficientunet_b3_seg
from .MTL_model_v2 import DeepLab
from .MTL_model_v2 import DeepLab_seg
from .MTL_model_v2 import DeepLab_cls
from .MTL_model_v2 import ResUnet,ResUnetPlusPlus
